name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Maven cache
      uses: actions/cache@v1
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: npm cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install karma
      run: sudo npm install -g karma-cli
    - name: Install dependencies
      run: lein deps
  ci:
    - name: Run tests
      run: lein ci
